keys:
    - &adam age1308nxr6h57dvujczq29kc8du8qylnma8m5utn905en758qck0fwssmytrm
    - &ramiel age1l89lumsrstssgjmw40n9u8pvq2mppcm4kfp4s4dc5v98tsvy33pqgfgl32

creation_rules:
    - path_regex: secrets/adam\.yaml$
      key_groups:
          - age:
                - *adam
    - path_regex: secrets/ramiel\.yaml$
      key_groups:
          - age:
                - *ramiel
