add_newline = false
format = "$directory$character"
right_format = "$status$git_branch$git_status$username$hostname"

[character]
error_symbol = "[❯](red)[❯](yellow)[❯](green)"
success_symbol = "[❯](red)[❯](yellow)[❯](green)"
vicmd_symbol = "[❮](green)[❮](yellow)[❮](red)"

[cmd_duration]
format = "[$duration]($style) "

[directory]
fish_style_pwd_dir_length = 1
style = "blue"
truncation_length = 1
truncation_symbol = ""

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "red"

[hostname]
format = "[$hostname]($style) "
ssh_only = true
style = "blue"

[line_break]
disabled = true


[status]
disabled = false
symbol = "✘ "

[username]
format = "[$user@]($style)"
show_always = false
style_root = "bold red"
style_user = "blue"
