trashGuideUrl: https://github.com/LaurenceBarnes/Guides

sonarrEnabled: true
radarrEnabled: true
readarrEnabled: false
lidarrEnabled: false

sonarr:
  instance1:
    base_url: http://127.0.0.1:8989/sonarr
    api_key: !secret SONARR_API_KEY

    include:
      - template: dca7e5e9e99c703bcbdaaa471dd40e98 # [German] HD Bluray + WEB
        source: TRASH
      - template: 6fe5937e1dcc2269e23b49eb46dfe6d6 # [German] Anime HD Bluray + WEB
        source: TRASH
      - template: 3b0fa37fddaaefc931b75f2889d4b4f5 # [German] UHD Bluray + WEB
        source: TRASH

    custom_formats:
      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
        assign_scores_to:
          - name: "[German] Anime HD Bluray + WEB"
            score: 1000
      - trash_ids:
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: "[German] Anime HD Bluray + WEB"
            score: 0
          - name: "[German] HD Bluray + WEB"
            score: -35000
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: -35000
      - trash_ids:
          - 505d871304820ba7106b693be6fe4a9e # HDR
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: 500
      - trash_ids:
          - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: 1000
      - trash_ids:
          - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: 100
      - trash_ids:
          - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback)
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: -10000

radarr:
  instance1:
    base_url: http://127.0.0.1:7878/radarr
    api_key: !secret RADARR_API_KEY

    include:
      - template: 2b90e905c99490edc7c7a5787443748b # [German] HD Bluray + WEB
        source: TRASH
      - template: bf3cc2e99ad9a804a9b0d0e538e1fbba # [German] Anime HD Bluray + WEB
        source: TRASH
      - template: 27cc3d153c0a799fd139ef1ff4c4cc42 # [German] UHD Bluray + WEB
        source: TRASH

    custom_formats:
      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: "[German] Anime HD Bluray + WEB"
            score: 1000
      - trash_ids:
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: "[German] Anime HD Bluray + WEB"
            score: 0
          - name: "[German] HD Bluray + WEB"
            score: -35000
      - trash_ids:
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: -35000
      - trash_ids:
          - 493b6d1dbec3c3364c59d7607f7e3405 # HDR
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: 500
      - trash_ids:
          - b337d6812e06c200ec9a2d3cfa9d20a7 # DV Boost
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: 1000
      - trash_ids:
          - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: 100
      - trash_ids:
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (w/o HDR fallback)
        assign_scores_to:
          - name: "[German] UHD Bluray + WEB"
            score: -10000
